/*
 * This source file was generated by the Gradle 'init' task
 */
package com.waterloorocketry.dragoverride;

import info.openrocket.core.plugin.PluginModule;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
