/*
 * This source file was generated by the Gradle 'init' task
 */
package com.waterloorocketry.dragoverride;

class AppTest {
//    @Test void appHasAGreeting() {
//        PidTuner classUnderTest = new PidTuner();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
}
