/*
 * This source file was generated by the Gradle 'init' task
 */
package com.waterloorocketry.dragoverride;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
//    @Test void appHasAGreeting() {
//        PidTuner classUnderTest = new PidTuner();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
}
